# Build stage
#
FROM maven:3.8.5-openjdk-17-slim AS build
COPY ./src /home/app/src
COPY ./pom.xml /home/app
RUN mvn clean install -f /home/app/pom.xml -DskipTests

#
# Package stage
#
#FROM openjdk:8-jdk-alpine
FROM openjdk:17-slim
COPY --from=build /home/app/target/app.jar /usr/local/lib/app.jar
RUN apt-get update -y && \
    apt-get install -y tzdata
ENV TZ=America/Sao_Paulo
EXPOSE 8083

ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar"]